version: '3.8'

services:
  mysql-ccc:
    image: mysql:8.0
    container_name: mysql-componentes-capas
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ccc_user
      MYSQL_PASSWORD: ccc_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_ccc_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_ccc_data:
